swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  # Récupération des comptes bancaires de l'utilisateur
  /user/accounts:
    get:
      tags:
        - User Transactions
      summary: Récupère tous les comptes bancaires de l'utilisateur
      security:
        - Bearer: []
      responses:
        200:
          description: Comptes récupérés avec succès
          schema:
            $ref: "#/definitions/AccountsResponse"
        401:
          description: Une authentification est nécessaire pour accéder à la ressource
        403:
          description: Vous n'avez pas les autorisations nécessaires pour accéder à ce compte.
        404:
          description: Compte non trouvé
        500:
          description: Erreur interne du serveur

  # Récupération, par date de la liste des transactions d'un compte
  /account/{accountId}/transactions:
    get:
      tags:
        - User Transactions
      summary: Récupérer la liste des transactions d'un compte bancaire par dates
      security:
        - Bearer: []
      parameters:
        - name: accountId
          in: path
          description: ID du compte
          required: true
          type: integer
        - name: fromDate
          in: query
          description: Date de début de la transaction
          required: false
          type: string
        - name: toDate
          in: query
          description: Date de fin de la transaction
          required: false
          type: string
      responses:
        200:
          description: Transactions récupérées avec succès
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionsResponse"
        401:
          description: Authentification requise pour accéder à la ressource.
        403:
          description: Vous n'avez pas les autorisations nécessaires pour accéder à la ressource.
        404:
          description: transactions non trouvé
        500:
          description: Erreur interne du serveur

  # Récupération d'une transaction en fonction de son ID
  /account/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - User Transactions
      summary: Récupérer les détails d'une transaction par ID
      security:
        - Bearer: []
      parameters:
        - in: path
          name: accountId
          description: ID du compte
          type: integer
          required: true
        - in: path
          name: transactionId
          description: ID de transaction
          required: true
          type: integer
      responses:
        200:
          description: Transactions récupérées avec succès
          schema:
            $ref: "#/definitions/TransactionsResponse"
        401:
          description: Authentification requise pour accéder à la ressource.
        403:
          description: Vous n'avez pas les autorisations nécessaires pour accéder à la ressource.
        404:
          description: transactions non trouvé
        500:
          description: Erreur interne du serveur

  # Maj de la catégorie
  /transactions/{transactionId}/category:
    patch:
      tags:
        - User Transactions
      summary: Modifier la catégorie d'une transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: ID de la transaction
          required: true
          type: integer
        - in: body
          name: category
          description: Modifier la catégorie d'une transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionCategory"
      responses:
        200:
          description: La catégorie de la transaction a été modifiée avec succès
          schema:
            $ref: "#/definitions/TransactionCategory"
        401:
          description: Authentification requise pour accéder à la ressource.
        403:
          description: Vous n'avez pas les autorisations nécessaires pour accéder à la ressource.
        404:
          description: Transaction non trouvée
        500:
          description: Erreur interne du serveur

  # Maj de la note
  /transactions/{transactionId}/note:
    patch:
      tags:
        - User Transactions
      summary: Modifier une note d'une transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: ID de la transaction
          required: true
          type: integer
        - in: body
          name: note
          description: Modifier la note de la transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionNote"
      responses:
        200:
          description: Note modifiée avec succès
          schema:
            $ref: "#/definitions/TransactionResponseNote"
        401:
          description: Authentification requise pour accéder à la ressource.
        403:
          description: Vous n'avez pas les autorisations nécessaires pour accéder à la ressource.
        404:
          description: Échec de la modification de la note
        500:
          description: Erreur interne du serveur

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  AccountsResponse:
    type: object
    properties:
      accountID:
        type: string
        description: ID du compte
      accountName:
        type: string
        description: nom du compte
      accountCurrency:
        type: string
        description: devise du compte
      currentBalance:
        type: number
        description: solde du compte courant
        format: double
  TransactionsResponse:
    type: object
    properties:
      transactionId:
        type: integer
        description: ID de la transation
      transactionType:
        type: string
        description: Type de la transation
      date:
        type: string
        format: date-time
      amount:
        type: number
      balance:
        type: number
        format: double
      category:
        type: string
      note:
        type: string
  TransactionCategory:
    type: object
    properties:
      category:
        type: string
  TransactionNote:
    type: object
    properties:
      note:
        type: string
  TransactionResponseNote:
    type: object
    properties:
      note:
        type: string
      noteID:
        type: string
