swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  # Récupération du compte bancaire
  /user/account/{accountId}:
    get:
      tags:
        - User Transactions
      summary: Récupére un compte bancaire par ID
      security:
        - Bearer: []
      parameters:
        - in: path
          name: accountId
          description: ID du compte
          type: integer
          required: true
      responses:
        200:
          description: Compte récupéré avec succès
          schema:
            $ref: "#/definitions/AccountsResponse"
        400:
          description: Champs invalides
        500:
          description: Erreur interne du serveur

  # Récupération la liste des transactions d'un compte en fonction de l'ID du compte
  /account/{accountId}/transactions:
    get:
      tags:
        - User Transactions
      summary: Récupérer la liste des transactions d'un compte bancaire par ID
      security:
        - Bearer: []
      parameters:
        - name: accountId
          in: path
          description: ID du compte
          required: true
          type: integer
        - name: fromDate
          in: query
          description: Date de début de la transaction
          required: false
          type: string
        - name: toDate
          in: query
          description: Date de fin de la transaction
          required: false
          type: string
      responses:
        200:
          description: Transactions récupérées avec succès
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionsResponse"
        404:
          description: Compte non trouvé
        500:
          description: Erreur interne du serveur

  # Récupération d'une transaction en fonction de son ID
  /account/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - User Transactions
      summary: Récupérer les détails d'une transaction par ID
      security:
        - Bearer: []
      parameters:
        - in: path
          name: accountId
          description: ID du compte
          type: integer
          required: true
        - in: path
          name: transactionId
          description: ID de transaction
          required: true
          type: integer
      responses:
        200:
          description: Transactions récupérées avec succès
          schema:
            $ref: "#/definitions/TransactionsResponse"
        404:
          description: Échec de la récupération de la transaction
        500:
          description: Erreur interne du serveur

  # Maj de la catégorie
  /transactions/{transactionId}/category:
    put:
      tags:
        - User Transactions
      summary: Mettre à jour la catégorie d'une transaction par ID
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: ID de la transaction
          required: true
          type: integer
        - in: body
          name: category
          description: Modifier la catégorie d'une transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionCategory"
      responses:
        200:
          description: La catégorie de la transaction a été modifiée avec succès
          schema:
            $ref: "#/definitions/TransactionCategory"
        404:
          description: Transaction non trouvée
        500:
          description: Erreur interne du serveur

  # Ajout de la note
  /transactions/{transactionId}/note:
    post:
      tags:
        - User Transactions
      summary: Ajouter une note à une transaction par ID
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: ID de la transaction
          required: true
          type: integer
        - in: body
          name: note
          description: Nouvelle note de transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionNote"
      responses:
        200:
          description: Note ajoutée avec succès
          schema:
            $ref: "#/definitions/TransactionResponseNote"
        404:
          description: Note non créée
        500:
          description: Erreur interne du serveur

  # Maj de la note
  /transactions/{transactionId}/note/{noteId}:
    put:
      tags:
        - User Transactions
      summary: Mettre à jour une note d'une transaction par ID et note ID
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: ID de la transaction
          required: true
          type: integer
        - in: path
          name: noteId
          description: ID de la note
          required: true
          type: string
        - in: body
          name: note
          description: Modifier la note de la transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionNote"
      responses:
        200:
          description: Note modifiée avec succès
          schema:
            $ref: "#/definitions/TransactionResponseNote"
        404:
          description: Échec de la modification de la note
        500:
          description: Erreur interne du serveur

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  AccountsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: "#/definitions/Account"
  Account:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      currency:
        type: string
      balance:
        type: number
  TransactionsResponse:
    type: object
    properties:
      transactionId:
        type: integer
      transactionType:
        type: string
      date:
        type: string
        format: date-time
      amount:
        type: number
      balance:
        type: number
        format: double
      category:
        type: string
      note:
        type: string
  TransactionCategory:
    type: object
    properties:
      category:
        type: string
  TransactionNote:
    type: object
    properties:
      note:
        type: string
  TransactionResponseNote:
    type: object
    properties:
      note:
        type: string
      noteID:
        type: string
